Repository WildCodeSchool/lyon-js-sept21-p2-g2-back, pull requests merged in 2021-11, with the labels that each got.

#1 Express api
  .env
  .sample-env
  app.js
  package-lock.json
  package.json
Labels: Ready for prod

#4 Express api
  app.js
  db-config.js
  package-lock.json
  package.json
Labels: Fixed - ready for prod

#7 Express api
  app.js
  reset_db.sql
Labels: Ready for validation

#8 Setup comment section and link to db
  app.js
  reset_db.sql
Labels: Ready for prod

#10 fix bug
  app.js
  reset_db.sql
Labels: Ready for prod

#12 fix posts filter on destinations with no posts
  app.js
  reset_db.sql
Labels: Ready for prod

#14 clean
  app.js
Labels: Ready for prod
